version: '3'

services:
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5431:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sadaqa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local