FROM node:16.14-alpine

WORKDIR /home/app

COPY package.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./
COPY src ./src

RUN npm install

RUN npx prisma generate

RUN npm i -g @nestjs/cli

RUN chown -R node:node /home/app
USER node

EXPOSE 5000

CMD ["npm", "run", "start:dev"]
