export enum NotificationType {
    NEW_MESSAGE = 'NEW_MESSAGE',
    NEW_DONATION_POST = 'NEW_DONATION_POST',
    NEW_DONATION_REQUEST_POST = 'NEW_DONATION_REQUEST_POST',
    NEW_FAMILY_IN_NEED_POST = 'NEW_FAMILY_IN_NEED_POST',
    NEW_CALL_FOR_HELP_POST = 'NEW_CALL_FOR_HELP_POST',
}