export enum PostNotificationReason {
    POST_IN_RECEIVER_WILAYA = 'POST_IN_RECEIVER_WILAYA',
    LIKELY_HAVING_SIMILAR_DONATION = 'LIKELY_HAVING_SIMILAR_DONATION',
    LIKELY_HAVING_SIMILAR_DONATION_REQUEST = 'LIKELY_HAVING_SIMILAR_DONATION_REQUEST',
}