exports.POSTS_PICS_FILE_ID = "1xFClAxq6OgHy5L9ICjYd_jJbqp9p7mhW";
exports.USERS_PICS_FILE_ID = "1leFMw8VegeckILGRr6cfdxCWyQ8FWQjh";
exports.ASSOCIATIONS_DOCS_FILE_ID = "1lex82dPX_c7oPMRI6TkOwCjZArUma12u";
