name: Azure CD

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: npm
      - 
        name: Install Dependencies
        run: npm install
      -
        name: Run Tests
        run: npm test
  
  build: 
    name: Build / Push to ACR
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      -
        name: Build The Image
        run: docker build . --tag sadaqa.azurecr.io/sadaqa-server:${{ steps.package-version.outputs.current-version }}
      -
        name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      -
        name: Login To ACR
        uses: azure/docker-login@v1
        with:
          login-server: sadaqa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Push To ACR
        run: docker push sadaqa.azurecr.io/sadaqa-server:${{ steps.package-version.outputs.current-version }}
  
  deploy:
    name: Deploy to ACI
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      -
        name: Login To ACR
        uses: azure/docker-login@v1
        with:
          login-server: sadaqa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - 
        name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      -
        name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          name: sadaqa-server
          resource-group: sadaqa
          dns-name-label: sadaqa-server
          image: sadaqa.azurecr.io/sadaqa-server:${{ steps.package-version.outputs.current-version }}
          location: 'east us'
          ports: 80
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          secure-environment-variables: DATABASE_URL=${{ secrets.DATABASE_URL }} |
            CLIENT_URL=${{ secrets.CLIENT_URL }} |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} |
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} |
            GOOGLE_REDIRECTED_URL=${{ secrets.GOOGLE_REDIRECTED_URL }} |
            GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }} |
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
