name: CI

on:
  push:
    branches:
      - 'develop'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sadaqa_test

    env:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/sadaqa_test?schema=public'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.*'
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Setup the DB
        run: |
          npx prisma db push
          npx prisma db seed
      - name: Run Tests
        run: npm test

  integrate:
    name: Dockerize and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Build The Image
        run: docker build . --tag sadaqa-backend:${{ steps.package-version.outputs.current-version }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push To Docker Hub
        run: docker push sadaqa-backend:${{ steps.package-version.outputs.current-version }}
